name: Multi-Platform Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        force_bit: [DEFAULT, FORCE_64]
        include:
          - os: windows-latest
            cpp_compiler: cl
            force_bit: DEFAULT
          - os: ubuntu-latest
            cpp_compiler: g++
            force_bit: DEFAULT
          - os: ubuntu-latest
            cpp_compiler: clang++
            force_bit: DEFAULT
          - os: ubuntu-latest
            cpp_compiler: g++
            force_bit: FORCE_64
          - os: ubuntu-latest
            cpp_compiler: clang++
            force_bit: FORCE_64
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
          - os: ubuntu-latest
            cpp_compiler: cl
          - os: windows-latest
            force_bit: FORCE_64

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        ${{ matrix.force_bit == 'FORCE_32' && '-DBI_FORCE_32_BIT=ON' || '' }}
        ${{ matrix.force_bit == 'FORCE_64' && '-DBI_FORCE_64_BIT=ON' || '' }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
