name: Static Analysis

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: bi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy

    - name: Print clang-tidy version
      run: clang-tidy --version

    - name: Configure CMake
      run: |
        cmake -B build \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_CXX_COMPILER=clang++ \
        -S .
      working-directory: bi

    - name: Run clang-tidy
      run: clang-tidy -p build include/*.hpp src/*.hpp test/*.hpp src/*.cpp test/*.cpp --warnings-as-errors='*'
      working-directory: bi

  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: bi
    - name: Install cpplint
      run: pip install cpplint
    - name: Print cpplint version
      run: pip show cpplint
    - name: Run cpplint
      run: cpplint --root=.. src/* include/* test/*
      working-directory: bi

  clang-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: bi

    - name: Install clang-format
      run: |
        sudo apt-get update
        wget https://apt.llvm.org/llvm.sh
        sudo chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-format-17

    - name: Print clang-format version
      run: clang-format-17 --version

    - name: Check format
      run: |
        find include/ src/ test/ -iname '*.hpp' -o -iname '*.cpp' | while read file; do
          clang-format-17 "$file" | diff "$file" -
        done
      working-directory: bi
